"""added amount in currencies

Revision ID: 7e2a9aed0504
Revises: cd70c60317f4
Create Date: 2018-04-04 21:25:42.983907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e2a9aed0504'
down_revision = 'cd70c60317f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_currencies', sa.Column('amount', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_currencies', 'amount')
    # ### end Alembic commands ###
