"""added symbol

Revision ID: a52770687d22
Revises: 7e2a9aed0504
Create Date: 2018-04-04 22:23:11.306246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a52770687d22'
down_revision = '7e2a9aed0504'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_currencies', sa.Column('symbol', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_currencies', 'symbol')
    # ### end Alembic commands ###
