"""UserCurrencies table

Revision ID: cd70c60317f4
Revises: eb276b95e371
Create Date: 2018-02-12 20:13:12.741423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd70c60317f4'
down_revision = 'eb276b95e371'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_currencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=140), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_currencies')
    # ### end Alembic commands ###
